var first = 'Tanha';
var last = 'Reja';
var full = first + ' ' + last;
// console.log(full);
var age = 69;
var ageFloat = 69.99;
var ageTruth = false;
// console.log(typeof full);
// console.log(typeof age);
// console.log(typeof ageFloat);
// console.log(typeof ageTruth);
var today = new Date();
// console.log(today);
// console.log(typeof today);
var firstNumb = 0.1;
var secondNumb = 0.2;
var total = firstNumb + secondNumb;
// console.log(total);
total = parseFloat(total);
// console.log(total);
// console.log(total.toFixed(2));
var a = 15;
var b = 4;
var c = a / b;
var d = a % b;
console.log(c);
console.log(d);