var vowels = ['a','e','i','o','u'];
// console.log(vowels);
// console.log(vowels.length);
// console.log(vowels.indexOf('a'));
// console.log(vowels.indexOf('u'));
// console.log(vowels.indexOf('b'));
// console.log(vowels[2]);
var alph = ['a','e','i','o','u'];
alph.push('b');
// console.log(alph);
alph.pop();
alph.pop();
// console.log(alph);
// alph.shift();
// console.log(alph);